In [2]:
import numpy as np

In [9]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
c = np.zeros((2, 3)) 
d = np.ones((3, 2)) 
e = np.eye(3) 
# print(b)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
s = "Hi, my name is Rishav shrestha"
count = 0
vowels = "aeiouAEIOU"

for i in range(len(s)):
    if s[i] in vowels:
        count += 1

print('The number of vowels is', count)


The number of vowels is 8


In [4]:
# random array
random_arr = np.random.rand(3)
# random_arr=np.array(([2,3],[4,7]))
print(random_arr)

[0.69900053 0.44866955 0.26371404]


In [14]:
# creating 10 random integers
import numpy as np

# Create an array of 10 random integers between 1 and 100
random_array = np.random.randint(1, 101, size=5)

print("Random Integer Array:")
print(random_array)


Random Integer Array:
[46  5 49 70 79]


In [28]:
import numpy as np
arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [34]:
# datatype
a = np.array([1, 2, 3], dtype='complex')
print(a.dtype)
print(a)

complex128
[1.+0.j 2.+0.j 3.+0.j]


In [37]:
a=np.arange(1, 10, 2) 
print(a)

[1 3 5 7 9]


In [39]:
# srt to arr
s="1,2,3,4,5"
arr=np.array(s.split(','),dtype=str)
print(arr)

['1' '2' '3' '4' '5']


In [46]:
# 2d
a = np.array([[1, 2], [3, 4]])
print(a)
print(a.T)
print(a.ndim)

# 3d
d = np.array([[[1], [2]], [[3], [4]]])
print(d)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
2
[[[1]
  [2]]

 [[3]
  [4]]]


In [45]:
a = np.array([{"name": "Ram"}, {"name": "Shyam"}], dtype=object)
print(a[0]["name"])  
print(a.shape)


Ram
(2,)


In [51]:
# indexing
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1 ,2])
print(arr[0,2]+arr[1,2])

6
9


In [64]:
# slicing
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[-2:2:-2])

[8 6 4]


In [10]:
a = np.logspace(  1, 10, num=3, base=2)
print(a)

[   2.         45.254834 1024.      ]


In [ ]:
# past question
s =np.random.randint(1,100,size=10)
print(s)
r=np.sort(s)
print(r)

[12 11 58 67 25 83 38 45 69 56]
[11 12 25 38 45 56 58 67 69 83]


In [21]:
# sorting
arr = np.array([[6,5,7], [1,9,3]])
print(np.sort(arr, axis=0))


[[1 5 3]
 [6 9 7]]


In [ ]:
import numpy as np
names = np.array(['banana', 'apple', 'banana'])
marks = np.array([90, 95, 85])

# last key is primary: (secondary, primary)
indices = np.lexsort((marks, names))
print(indices)        # [1 2 0]
print(names[indices])
print(marks[indices])


[1 2 0]
['apple' 'banana' 'banana']
[95 85 90]
